added script to generate a spinning gif of the logo
f-klubben/logo pull request #4
Opened 2023-10-25 20:41 UTC by Mast3rwaf1z

this script uses the `centered-logo.png` file by default, but takes a different image as argument

Also added is a centered version of the logo as a PNG. Pillow does not support SVG.

2023-10-27 12:43 UTC, Mast3rwaf1z commented
#5 should be implemented with the centered logo in this PR

it was centered in GIMP by isolating the circle, centering the circle, noting down the coordinate difference. Then moving the entire logo by this difference

![image](https://github.com/f-klubben/logo/assets/32744171/0ae48bff-30dd-4514-8513-7286cd6f8c5a)

2024-09-25 08:26 UTC, atjn requested changes
Very cool!

It seems pretty chaotic to put all this into the root directory. Could you put the script in a subdirectory and make it output the spinners there? Then you could also add a README with a few notes on how to run the script and what it outputs :)

If you want, you can leave `centered-logo.png` in the root directory.

I assume that you meant to delete `logo_centered.png`?

2024-09-25 08:26 UTC, atjn commented on .gitignore
> +*.gif
Please namespace this, otherwise we can never submit a gif source file to this repo.

2026-03-18 10:38 UTC, DeeKahy commented
Since this pr went radio silent and i cannot make any changes here i made a new one that should fix the folder and namespace stuff.

2026-03-18 10:48 UTC, krestenlaust commented
Solved in #16

2026-03-18 10:48 UTC, closed without merging